version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:    
    interval: "daily"  
    time: "08:00" 
  versioning-strategy: increase # Update package.json too
  groups:
    patterns:
      update-types:
        - patch
        - minor
 
