version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:    
    interval: "daily"  
    time: "09:00"
    timezone: "Europe/Moscow"    
  workflow_dispatch:  
  versioning-strategy: increase # Update package.json too
  groups:
    patterns:
      update-types:
        - patch
        - minor
