version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: "daily"  
    time: "09:00"
    timezone: "Europe/Moscow"
  versioning-strategy: increase # Update package.json too
  groups:
    patterns:
      update-types:
        - patch
        - minor
        
notifications:
  - type: "email"
    recipients:
      - metaller7440326@gmail.com
    on:
      - "update-failure"
      - "security-update-available"
      - "pull-request-created"
