name: cicd

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      
jobs:
  semgrep:
    if: true == false
    name: SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep    
    steps:       
      - uses: actions/checkout@v4
      - run: semgrep ci
  
  build-and-push:
    name: push
    if: true == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: docker.io   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Validate Docker Hub credentials
        run: |
          echo ${{ env.TEST }}          
          if [ -z "${{ secrets.DOCKERHUB_REPO }}" || -z "${{ secrets.DOCKERHUB_USER }}" || -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "::error::Docker Hub credentials not set!"
            exit 1
          fi
      
      - name: Log in to Docker Hub        
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract commit SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.sha.outputs.short_sha }}
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_REPO }}:latest          
            
  dast:
    name: DAST    
    strategy:
      matrix:
        node: [22.4.1]
        os: [ubuntu-latest]    
    runs-on: ${{ matrix.os }}
    env:
      REGISTRY: docker.io  

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
      - name: Run container
        run: |
          docker run -d --network host --name me -p 8081:8081 -e mongodb://mongo:27017/ ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_REPO }}:latest          
          docker ps -a
          curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8081
                
  deploy:
    name: deploy
    if: true == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}    
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Run remote script directly
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} ${{ secrets.SSH_SCRIPT }}
