name: cicd

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      
jobs:
  secret_scan:
    name: secret_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: gitleaks/gitleaks-action@v2
        with:
          redact: true 
            
  sast:
    if: true == false
    name: SAST
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep    
    steps:       
      - uses: actions/checkout@v4
      - run: semgrep ci
  
  push:
    if: true == false
    name: push    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: docker.io   
    steps:     
      - name: Validate Docker Hub credentials
        run: |
          echo ${{ env.TEST }}          
          if [ -z "${{ secrets.DOCKERHUB_REPO }}" || -z "${{ secrets.DOCKERHUB_USER }}" || -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "::error::Docker Hub credentials not set!"
            exit 1
          fi
      
      - name: Log in to Docker Hub        
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract commit SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_REPO }}:${{ steps.sha.outputs.short_sha }}
            ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_REPO }}:latest          
            
  dast:
    if: true == false
    name: DAST        
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io  

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASS }}

    steps:
      - name: Run container
        run: |
          docker run -d --network host --name me -e ME_CONFIG_SITE_COOKIESECRET=cookiesecret -e ME_CONFIG_SITE_SESSIONSECRET=sessionsecret -e ME_CONFIG_MONGODB_URL=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_pass }}@localhost:27017/ ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_REPO }}:latest          
          docker ps
          curl -LI --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8081
          docker logs me
          
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8081'
          cmd_options: '-t http://localhost:8081'
      
      - name: Stop containers
        run: |
          docker stop me || true
          docker rm me || true
          
  deploy:
    name: deploy
    if: true == false
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}    
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Run remote script directly
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} ${{ secrets.SSH_SCRIPT }}
