name: cicd

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
env:
  REGISTRY: docker.io
  IMAGE_NAME: metaller000/me-netology

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Validate Docker Hub credentials
        run: |
          echo ${{ env.TEST }}          
          if [ -z "${{ secrets.dockerhub.DOCKERHUB_USER }}" ] || [ -z "${{ secrets.dockerhub.DOCKERHUB_TOKEN }}" ]; then
            echo "::error::Docker Hub credentials not set!"
            exit 1
          fi
      
      - name: Log in to Docker Hub        
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub.DOCKERHUB_USER }}
          password: ${{ secrets.dockerhub.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
